# Generated by Django 5.1.7 on 2025-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_roofplantationproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="recyclingcenter",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="recyclingcenter",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
